export const SELECT_ROOM = "SELECT_ROOM";
export const SOCKET_GET_ROOMS = "SOCKET_GET_ROOMS";
export const SOCKET_CREATE_ROOM = "SOCKET_CREATE_ROOM";
export const SOCKET_DELETE_ROOM = "SOCKET_DELETE_ROOM";
