export const FETCH_CHECK_TOKEN_USER = "FETCH_CHECK_TOKEN_USER";
export const FETCH_CHECK_TOKEN_USER_PENDING =
	"FETCH_CHECK_TOKEN_USER_PENDING";
export const FETCH_CHECK_TOKEN_USER_ERROR =
	"FETCH_CHECK_TOKEN_USER_ERROR";

export const FETCH_SING_IN_PENDING = "FETCH_SING_IN_PENDING";
export const FETCH_SING_IN_SUCCESS = "FETCH_SING_IN_SUCCESS";
export const FETCH_SING_IN_ERROR = "FETCH_SING_IN_ERROR";

export const FETCH_SING_UP_PENDING = "FETCH_SING_UP_PENDING";
export const FETCH_SING_UP_SUCCESS = "FETCH_SING_UP_SUCCESS";
export const FETCH_SING_UP_ERROR = "FETCH_SING_UP_ERROR";
