export const FETCH_SING_IN_PENDING = "FETCH_SING_IN_PENDING";
export const FETCH_SING_IN_SUCCESS = "FETCH_SING_IN_SUCCESS";
export const FETCH_SING_IN_ERROR = "FETCH_SING_IN_ERROR";

export const FETCH_SING_OUT_PENDING = "FETCH_SING_OUT_PENDING";
export const FETCH_SING_OUT_SUCCESS = "FETCH_SING_OUT_SUCCESS";
export const FETCH_SING_OUT_ERROR = "FETCH_SING_OUT_ERROR";
